### ISSUE TITLE
uniform_int_distribution has UB with uint8_t

### ISSUE THREAD

**Issue by xjossy** [ashvardanian/CppBenchSubstrSearch#1]
As for https://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution , the `uniform_int_distribution` supports only template arguments of the following list:
`short`, `int`, `long`, `long long`, `unsigned short`, `unsigned int`, `unsigned long`, or `unsigned long long`, while you have `uint8_t` two times. This follows UB.

Also, `uniform_int_distribution<uint8_t>` is not supported also by VS compiler.

**Comment by ashvardanian** [comment]
Thanks for the notice! Feel free to submit a pull request

**Comment by ashvardanian** [comment]
This should do: 1cd4d820062f8697b5135e9d3e9bca67706fb076
