### ISSUE TITLE
Searching was optimized out

### ISSUE THREAD

**Issue by xjossy** [ashvardanian/CppBenchSubstrSearch#2]
Searching can be optimized out. For example, VS compiler does this.
Probably, you should do `bm::DoNotOptimize` that way:

```  
enumerate_matches(buffer_span, needles[state.iterations() % needles.size()], engine, [](size_t s) {
       bm::DoNotOptimize(s);
});
```

**Comment by ashvardanian** [comment]
Thanks, done: 1cd4d820062f8697b5135e9d3e9bca67706fb076
